"""
Referral model — digital referral ticket generated by the triage engine.
"""

from sqlalchemy import Column, String, Integer, Float, DateTime, Boolean, Text, ForeignKey
from sqlalchemy.orm import relationship
from datetime import datetime
from database.db import Base


class Referral(Base):
    __tablename__ = "referrals"

    id = Column(String, primary_key=True, index=True)          # e.g. REF-20240915-0001
    patient_id = Column(String, ForeignKey("patients.id"), nullable=False)
    asha_worker_id = Column(String, nullable=False)
    origin_phc_id = Column(String, nullable=True)              # Originating PHC (if any)
    destination_hospital_id = Column(String, ForeignKey("hospitals.id"), nullable=False)
    assigned_specialist_id = Column(String, nullable=True)

    # Triage result
    triage_score = Column(Integer, nullable=False)
    triage_priority = Column(String, nullable=False)           # CRITICAL / HIGH / MEDIUM / LOW
    triage_category = Column(String, nullable=True)            # cardiac / neurological / obstetric …
    triage_notes = Column(Text, nullable=True)

    # Status lifecycle
    status = Column(String, default="PENDING")
    # PENDING → ACCEPTED → IN_TRANSIT → ADMITTED → DIAGNOSED → DISCHARGED / CANCELLED

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    accepted_at = Column(DateTime, nullable=True)
    patient_arrived_at = Column(DateTime, nullable=True)
    admitted_at = Column(DateTime, nullable=True)
    discharged_at = Column(DateTime, nullable=True)

    # Transport
    transport_mode = Column(String, nullable=True)             # ambulance / private / government van
    estimated_arrival_minutes = Column(Integer, nullable=True)

    # Diagnosis & medication (filled by hospital)
    diagnosis = Column(Text, nullable=True)
    medication_prescribed = Column(Text, nullable=True)
    follow_up_date = Column(DateTime, nullable=True)
    follow_up_notes = Column(Text, nullable=True)

    # Notification sent flag
    hospital_notified = Column(Boolean, default=False)

    # Relationships
    patient = relationship("Patient", back_populates="referrals")
    hospital = relationship("Hospital", back_populates="referrals")
